# Expose your documentation as JSON swagger compliant
when@dev:
    app.swagger:
        path: /doc.json
        methods: GET
        defaults: { _controller: nelmio_api_doc.controller.swagger }

    app.swagger.areas:
        path: /doc/{area}.json
        methods: GET
        defaults: { _controller: nelmio_api_doc.controller.swagger, area: default }

    app.swagger_ui:
        path: /doc/{area}
        methods: GET
        defaults: { _controller: nelmio_api_doc.controller.swagger_ui, area: default }
