services:
    _defaults:
        public: true
        autowire: true

    App\Module\Language\Infrastructure\Query\GetSpeedComparisonQuery: ~
    App\Module\Language\Infrastructure\Query\GetMostPopularQuery: ~
